title: Quantics Knowledge Base
remote_theme: pages-themes/cayman@v0.2.0
repository_url: https://github.com/KM-2323/documentation_intro
toc_min_headings: 3
footer_links:
  - title: Home
    url: /
  - title: Born-Oppenheimer
    url: /02_Born_Oppenheimer_and_Nonadiabaticity/
  - title: Direct Dynamics
    url: /05_Direct_Dynamics/
  - title: Diabatisation
    url: /06_diabatisation_deeperdive/
  - title: References
    url: /10_References_Guides/
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: "" # An empty string means this applies to all files in the project
    values:
      layout: "custom"
      toc: true
  - scope:
      path: "00_project_overview"
    values:
      section_title: "Project Overview"
      section_url: "/00_project_overview/"
  - scope:
      path: "01_Primer"
    values:
      section_title: "Primer"
  - scope:
      path: "02_Born_Oppenheimer_and_Nonadiabaticity"
    values:
      section_title: "Born-Oppenheimer and Nonadiabaticity"
      section_url: "/02_Born_Oppenheimer_and_Nonadiabaticity/"
  - scope:
      path: "02_Born_Oppenheimer_and_Nonadiabaticity/beginer"
    values:
      section_title: "Born-Oppenheimer and Nonadiabaticity"
      section_url: "/02_Born_Oppenheimer_and_Nonadiabaticity/"
      subsection_title: "Beginner"
  - scope:
      path: "02_Born_Oppenheimer_and_Nonadiabaticity/intermediates"
    values:
      section_title: "Born-Oppenheimer and Nonadiabaticity"
      section_url: "/02_Born_Oppenheimer_and_Nonadiabaticity/"
      subsection_title: "Intermediates"
  - scope:
      path: "02_Born_Oppenheimer_and_Nonadiabaticity/advanced"
    values:
      section_title: "Born-Oppenheimer and Nonadiabaticity"
      section_url: "/02_Born_Oppenheimer_and_Nonadiabaticity/"
      subsection_title: "Advanced"
  - scope:
      path: "02_Born_Oppenheimer_and_Nonadiabaticity/derivations"
    values:
      section_title: "Born-Oppenheimer and Nonadiabaticity"
      section_url: "/02_Born_Oppenheimer_and_Nonadiabaticity/"
      subsection_title: "Derivations"
  - scope:
      path: "04_vMCG"
    values:
      section_title: "vMCG Family"
      section_url: "/04_vMCG/"
  - scope:
      path: "04_vMCG/derivations"
    values:
      section_title: "vMCG Family"
      section_url: "/04_vMCG/"
      subsection_title: "Derivations"
  - scope:
      path: "03_MCTDH_Family" 
    values:
      section_title: "MCTDH Family"
      section_url: "/03_MCTDH_Family/"
  - scope:
      path: "05_Direct_Dynamics"
    values:
      section_title: "Direct Dynamics"
      section_url: "/05_Direct_Dynamics/"
  - scope:
      path: "06_diabatisation_deeperdive"
    values:
      section_title: "Diabatisation Deep Dive"
      section_url: "/06_diabatisation_deeperdive/"
  - scope:
      path: "06_diabatisation_deeperdive/intermediates"
    values:
      section_title: "Diabatisation Deep Dive"
      section_url: "/06_diabatisation_deeperdive/"
      subsection_title: "Theory and Main Idea"
  - scope:
      path: "06_diabatisation_deeperdive/code+breakdown"
    values:
      section_title: "Diabatisation Deep Dive"
      section_url: "/06_diabatisation_deeperdive/"
      subsection_title: "Code Breakdown"
  - scope:
      path: "06_diabatisation_deeperdive/derivations"
    values:
      section_title: "Diabatisation Deep Dive"
      section_url: "/06_diabatisation_deeperdive/"
      subsection_title: "Derivations"
      subsection_url: "/06_diabatisation_deeperdive/derivations/"
  - scope:
      path: "06_diabatisation_deeperdive/worked_examples"
    values:
      section_title: "Diabatisation Deep Dive"
      section_url: "/06_diabatisation_deeperdive/"
      subsection_title: "Worked Examples"
      subsection_url: "/06_diabatisation_deeperdive/worked_examples/"
  - scope:
      path: "06_diabatisation_deeperdive/specialised_propagation_diabatisation_deepdive"
    values:
      section_title: "Diabatisation Deep Dive"
      section_url: "/06_diabatisation_deeperdive/"
      subsection_title: "Specialised Topics"
      subsection_url: "/06_diabatisation_deeperdive/specialised_propagation_diabatisation_deepdive/"
  - scope:
      path: "06_diabatisation_deeperdive/specialised_propagation_diabatisation_deepdive/split_diabatic_representations_and_residual_couplings"
    values:
      section_title: "Diabatisation Deep Dive"
      section_url: "/06_diabatisation_deeperdive/"
      subsection_title: "Specialised Topics"
      subsection_url: "/06_diabatisation_deeperdive/specialised_propagation_diabatisation_deepdive/"
      subsubsection_title: "Connections between residual couplings and split diabatic representations"
  - scope:
      path: "09_electronic_structure_methods"
    values:
      section_title: "Electronic Structure Methods"
      section_url: "/09_electronic_structure_methods"
  - scope:
      path: "10_References_Guides"
    values:
      section_title: "References and Guides"
      section_url: "/10_References_Guides/"
  - scope:
      path: "derivations"
    values:
      section_title: "Derivations"
  - scope:
      path: "derivations/intro"
    values:
      section_title: "Derivations"
      subsection_title: "Intro"
